backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "people"
    label: "People"
    folder: "src/pages/people"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "people"}
      - {label: "Path", name: "path", widget: "string"}
      - {label: "Name", name: "title", widget: "string"}
      - {label: "Role", name: "role", widget: "string"}
      - {label: "Description", name: "body", widget: "markdown"}
